apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: helloworld-svc1
  namespace: ns2 
spec:
  exportTo:
   - "."
  hosts:
  - helloworld-svc1
  location: MESH_INTERNAL
  ports:
  - number: 80
    name: http
    protocol: HTTP
  resolution: DNS
  endpoints:
  - address: helloworld-svc1.ns1.svc.cluster.local 

  

