apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: helloworld-svc1
  namespace: ns1
spec:
  hosts:
    - svc1.helloworld.com
  gateways:
  - istio-system/my-gateway  
  http:
  - route:
    - destination:
        host: helloworld-svc1
        subset: v1
      weight: 50
    - destination:
        host: helloworld-svc1
        subset: v2
      weight: 50
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld-svc1
  namespace: ns1
spec:
  host: helloworld-svc1
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2